/**
 * @file UnscheduledDiagnosticsTable.jsx
 * @description Diagnostic Table displaying requests that could not be scheduled by the solver,
 * including Feature 3 operator exclusion diagnostics.
 * @module components/UnscheduledDiagnosticsTable
 */

import React from 'react';
import PriorityBadge from './PriorityBadge';

export default function UnscheduledDiagnosticsTable({ blocks = [], onSelectBlock }) {
  if (!blocks.length) return null;

  return (
    <div className="panel" style={{ borderLeft: '4px solid #ef4444' }}>
      <div className="panel-header" style={{ background: 'rgba(239, 68, 68, 0.05)' }}>
        <div>
          <div className="panel-title" style={{ color: '#f87171' }}>
            <span>⚠ Unscheduled Requests Diagnostic Engine ({blocks.length})</span>
          </div>
          <div className="panel-subtitle">
            Causal reasoning generated by mathematical solver or operator exclusion preferences
          </div>
        </div>
      </div>

      <div className="panel-body">
        <div className="table-responsive">
          <table className="table">
            <thead>
              <tr>
                <th>Request ID</th>
                <th>Location</th>
                <th>Priority</th>
                <th>Duration</th>
                <th>Causal Diagnostic (Why was it not scheduled?)</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {blocks.map((u, idx) => (
                <tr key={u.request_id || idx}>
                  <td className="table-cell-mono">{u.request_id}</td>
                  <td>{u.location}</td>
                  <td><PriorityBadge priority={u.priority} /></td>
                  <td className="table-cell-mono">{u.duration_minutes || u.requested_duration || '--'} min</td>
                  <td style={{ color: '#fca5a5', maxWidth: 420, whiteSpace: 'normal' }}>
                    <strong>Diagnostic:</strong> {u.reason || 'Preempted by higher priority request or track possession collision.'}
                  </td>
                  <td>
                    <button
                      className="btn btn-secondary btn-sm"
                      onClick={() => onSelectBlock && onSelectBlock(u)}
                    >
                      Inspect
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
